version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      # - HF_TOKEN=your_huggingface_token_here
    restart: unless-stopped
